[project]
name = "secretary-faculty"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "certifi==2022.5.18.1",
    "charset-normalizer==2.0.12",
    "django-environ>=0.12.0",
    "idna==3.3",
    "psycopg2==2.9.10",
    "pytelegrambotapi==4.5.1",
    "python-dotenv==1.0.1",
    "requests==2.27.1",
    "urllib3==1.26.9",
]
